version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[github-actions] "
      prefix: "[github-actions] "

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "master"
    versioning-strategy: increase-if-necessary
    groups:
      "Python Dependencies":
        update-types:
          - "major"
          - "minor"
          - "patch"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[pip] "
      prefix: "[pip] "

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    versioning-strategy: increase-if-necessary
    groups:
      "NPM Dependencies":
        update-types:
          - "major"
          - "minor"
          - "patch"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[npm] "
      prefix: "[npm] "
